---

version: '3'

services:
  qa-api:
    container_name: qa-api
    build:
      # context: ./app
      dockerfile: ./Dockerfile.node 
    volumes:
      - ./app:/app
    ports:
      - 9303:3000
    tty: true
    stdin_open: true
